version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container_new
    environment:
      MYSQL_ROOT_PASSWORD: cisco
      MYSQL_DATABASE: cc_db
    ports:
      - "3307:3306"  # Changed host port from 3306 to 3307
    volumes:
      - mysql_data_new:/var/lib/mysql  # Changed volume name
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container_new
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: cisco
    ports:
      - "8081:80"  # Changed host port from 8080 to 8081
    depends_on:
      - db
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container_new
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"  # Changed host port from 3000 to 3001
    depends_on:
      - db
    restart: always
    volumes:
      - grafana_data_new:/var/lib/grafana  # Changed volume name

  splunk:
    image: splunk/splunk:latest
    container_name: splunk_container_new
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: Cisco1234!
    ports:
      - "8001:8000"  # Changed host port from 8000 to 8001
      - "8089:8088"  # Changed host port from 8088 to 8089
    restart: always

volumes:
  mysql_data_new:
  grafana_data_new:
