{
 "title": "Devices Health",
 "description": "a dashboard that shows the health of network devices (/dna/intent/api/v1/network-health)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Network Health",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cc_db",
     "rawSql": "SELECT total_devices, latest_health_score, monitored_healthy_devices, monitored_fair_health_devices, monitored_poor_health_devices, no_health_devices FROM cc_db.network_health_general LIMIT 50 "
    }
   ]
  },
  {
   "title": "Devices Type Count",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cc_db",
     "rawSql": "SELECT category, health_score, total_count FROM cc_db.network_health_category LIMIT 50 "
    }
   ]
  },
  {
   "title": "Clients Health Score",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "cc_db",
     "rawSql": "SELECT client_type, score_value FROM cc_db.client_scores LIMIT 50 "
    }
   ]
  },
  {
   "title": "Client Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "dataset": "cc_db",
     "rawSql": "SELECT client_type, client_count FROM cc_db.client_scores LIMIT 50 "
    }
   ]
  },
  {
   "title": "License Consumption",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cc_db",
     "rawSql": "SELECT entitled_essentials, deployed_essentials, entitled_advantage, deployed_advantage, device_type FROM cc_db.license_data_2 LIMIT 50 "
    }
   ]
  },
  {
   "title": "License Description",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "dataset": "cc_db",
     "rawSql": "SELECT device_type, deployed_license_description FROM cc_db.license_data_2 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Issues",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "cc_db",
     "rawSql": "SELECT issue_id, priority, category, description FROM cc_db.cc_issues2 LIMIT 50 "
    }
   ]
  }
 ]
}